Rails:
  Enabled: true

AllCops:
  # Rubyのバージョンを指定
  TargetRubyVersion: 2.5.5
  # 除外するファイル
  Exclude:
    - bin/*
    - db/**/*
    - config/**/*
    - Gemfile

# Missing magic comment # frozen_string_literal: true. を無視
Style/FrozenStringLiteralComment:
  Enabled: false

# Missing top-level class documentation comment. を無視
Style/Documentation:
  Enabled: false

# graphql_controller.rb を基準にする
# 1行の長さ
Metrics/LineLength:
  Max: 110

# メソッドの長さ
Metrics/MethodLength:
  Max: 15

# 引数の文字の最小値
Naming/UncommunicativeMethodParamName:
  MinNameLength: 1

# Use nested module/class definitions instead of compact style. を無視
Style/ClassAndModuleChildren:
  Enabled: false